#!/bin/ksh

# OpenBSD rc.d service file for exccd.
# Assumes a _exccd user is created with home directory /home/_exccd for block
# data, and application configuration in /etc/exccd.conf.
# All logs and crash traces are written to the daemon.info syslog facility,
# with exccd's built-in file logging and log rotation disabled by default.
# Save to /etc/rc.d/exccd and enable with 'pkg_scripts=exccd' in
# /etc/rc.conf.local.

daemon="/usr/local/bin/exccd"
daemon_flags="-C/etc/exccd.conf -A/home/_exccd --nofilelogging"
daemon_user=_exccd
daemon_logger=daemon.info

. /etc/rc.d/rc.subr

daemon="env LOGFLAGS=nodatetime ${daemon}"

rc_bg=YES
rc_reload=NO

rc_cmd $1
